version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/BLACK-OPNE"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/One-Core-Engine"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
