package org.lsposed.lsparanoid;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Source-compatibility marker used while LSParanoid bytecode transformation is disabled.
 * Existing @Obfuscate annotations can remain in source without changing generated bytecode.
 */
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.FIELD})
public @interface Obfuscate {
}
