<?php
/**
 * Telegram Bot for License Management
 * Features:
 * - Typing animation before each response
 * - List licenses (/list)
 * - Show connected devices with device name (/devices)
 * - License details (/info)
 * - Activate/revoke license (/activate, /revoke)
 * - Block/unblock license (force logout) (/block, /unblock)
 * - Block/unblock specific device (/deviceblock, /deviceunblock)
 * - Globally block/unblock an app (/blockapp, /unblockapp)
 * - Versioned broadcast (once per device) (/broadcast)
 * - Stop broadcast (/broadcaststop) – clears message and resets version
 */

require_once __DIR__ . '/conn.php';

// ========== CONFIG ==========
$botToken = trim((string) panel_config('TELEGRAM_BOT_TOKEN', ''));
$webhookSecret = trim((string) panel_config('TELEGRAM_WEBHOOK_SECRET', ''));
if ($botToken === '' || strlen($webhookSecret) < 16) {
    error_log('SDK Panel Telegram integration is not configured.');
    http_response_code(503);
    exit;
}
$providedSecret = (string) ($_SERVER['HTTP_X_TELEGRAM_BOT_API_SECRET_TOKEN'] ?? '');
if ($providedSecret === '' || !hash_equals($webhookSecret, $providedSecret)) {
    http_response_code(403);
    exit;
}
$apiUrl = "https://api.telegram.org/bot$botToken/";

// Fallback admin chat ID
$FALLBACK_ADMIN_ID = trim((string) panel_config('TELEGRAM_DEFAULT_ADMIN_CHAT_ID', ''));

// Fetch admin chat IDs from database
$adminRes = $conn->query("SELECT setting_value FROM server_settings WHERE setting_key='admin_chat_ids'");
$adminChatIds = [];
if ($adminRes && $row = $adminRes->fetch_assoc()) {
    $adminChatIds = array_map('trim', explode(',', $row['setting_value']));
}

// If no admins in DB, use fallback and insert
if (empty($adminChatIds)) {
    if ($FALLBACK_ADMIN_ID === '') {
        error_log('SDK Panel Telegram admin chat IDs are not configured.');
        http_response_code(503);
        exit;
    }
    $adminChatIds = [$FALLBACK_ADMIN_ID];
    $stmt = $conn->prepare(
        "INSERT INTO server_settings (setting_key, setting_value)
         VALUES ('admin_chat_ids', ?)
         ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)"
    );
    $stmt->bind_param('s', $FALLBACK_ADMIN_ID);
    $stmt->execute();
    $stmt->close();
}

// Get incoming update
$content = file_get_contents('php://input');
$update = json_decode($content, true);
if (!$update) exit;

$message = $update['message'] ?? null;
if (!$message) exit;

$chatId = (string) $message['chat']['id'];
$text = trim($message['text'] ?? '');

// Check if user is admin
if (!in_array($chatId, array_map('strval', $adminChatIds), true)) {
    sendMessage($chatId, "⛔ Unauthorized. This bot is private.");
    exit;
}

// Helper: send typing action before processing
function sendTyping($chatId) {
    global $apiUrl;
    file_get_contents($apiUrl . "sendChatAction?chat_id=$chatId&action=typing");
}

// Parse command and arguments
$parts = explode(' ', $text, 3);
$cmd = strtolower($parts[0]);
$arg1 = $parts[1] ?? '';
$arg2 = $parts[2] ?? '';

// Always send typing before processing
sendTyping($chatId);

switch ($cmd) {
    case '/start':
        $help = "⚡ONEBOX⚡ *License Bot*\n\n";
        $help .= "/list – Show recent licenses\n";
        $help .= "/devices – Show connected devices\n";
        $help .= "/info <key> – Show license details\n";
        $help .= "/activate <key> – Activate a license\n";
        $help .= "/revoke <key> – Deactivate a license\n";
        $help .= "/block <key> – Block a license (force logout)\n";
        $help .= "/unblock <key> – Unblock a license\n";
        $help .= "/deviceblock <device_id> – Block a specific device\n";
        $help .= "/deviceunblock <device_id> – Unblock a specific device\n";
        $help .= "/blockapp <package> – Globally block an app\n";
        $help .= "/unblockapp <package> – Unblock an app\n";
        $help .= "/broadcast <msg> – Send versioned broadcast (once per device)\n";
        $help .= "/broadcaststop – Stop current broadcast (clear message)";
        sendMessage($chatId, $help);
        break;

    case '/list':
        $res = $conn->query("SELECT license_key, package_name, expiry_date, status, force_logout, generated_by, created_at FROM licenses ORDER BY id DESC LIMIT 20");
        if ($res->num_rows == 0) {
            sendMessage($chatId, "No licenses found.");
        } else {
            $msg = "📋 *Recent Licenses:*\n\n";
            while ($row = $res->fetch_assoc()) {
                $status = $row['status'] ? '✅ Active' : '❌ Inactive';
                if ($row['force_logout']) $status .= ' (Blocked)';
                $msg .= "`{$row['license_key']}`\n";
                $msg .= "Package: {$row['package_name']}\n";
                $msg .= "Expires: {$row['expiry_date']}\n";
                $msg .= "Status: $status\n";
                $msg .= "Generated by: " . ($row['generated_by'] ?: 'N/A') . "\n";
                $msg .= "Created: {$row['created_at']}\n";
                $msg .= "---\n";
            }
            sendMessage($chatId, $msg);
        }
        break;

    case '/devices':
        $res = $conn->query("
            SELECT d.device_id, d.package_name, d.app_name, d.device_model, d.ip_address, d.license_key, d.last_seen, d.blocked,
                   l.expiry_date, l.force_logout
            FROM devices d
            LEFT JOIN licenses l ON d.license_key = l.license_key
            WHERE d.status = 'connected'
            ORDER BY d.last_seen DESC
            LIMIT 20
        ");
        if ($res->num_rows == 0) {
            sendMessage($chatId, "No connected devices.");
        } else {
            $msg = "📱 *Connected Devices:*\n\n";
            while ($row = $res->fetch_assoc()) {
                $msg .= "• *" . ($row['device_model'] ?: 'Unknown Device') . "*\n";
                $msg .= "  Device ID: `" . $row['device_id'] . "`\n";
                $msg .= "  Package: " . $row['package_name'] . "\n";
                $msg .= "  App: " . ($row['app_name'] ?: 'N/A') . "\n";
                $msg .= "  IP: " . $row['ip_address'] . "\n";
                $msg .= "  Key: " . $row['license_key'] . "\n";
                $msg .= "  Expiry: " . ($row['expiry_date'] ?: 'N/A') . "\n";
                $msg .= "  Last seen: " . $row['last_seen'] . "\n";
                $msg .= ($row['blocked'] ? "  ⛔ DEVICE BLOCKED\n" : "  ✅ Device Active\n");
                $msg .= ($row['force_logout'] ? "  ⛔ LICENSE BLOCKED\n" : "");
                $msg .= "---\n";
            }
            sendMessage($chatId, $msg);
        }
        break;

    case '/info':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /info <license_key>");
            break;
        }
        $key = $arg1;
        $stmt = $conn->prepare("SELECT * FROM licenses WHERE license_key=?");
        $stmt->bind_param("s", $key);
        $stmt->execute();
        $res = $stmt->get_result();
        if ($row = $res->fetch_assoc()) {
            $msg = "🔍 *License Details*\n";
            $msg .= "Key: `{$row['license_key']}`\n";
            $msg .= "Package: {$row['package_name']}\n";
            $msg .= "Expiry: {$row['expiry_date']}\n";
            $msg .= "Status: " . ($row['status'] ? '✅ Active' : '❌ Inactive') . "\n";
            $msg .= "Force Logout: " . ($row['force_logout'] ? 'Yes' : 'No') . "\n";
            $msg .= "Daemon: " . ($row['daemon'] ? 'Yes' : 'No') . "\n";
            $msg .= "Hide Root: " . ($row['hide_root'] ? 'Yes' : 'No') . "\n";
            $msg .= "Hide Xposed: " . ($row['hide_xposed'] ? 'Yes' : 'No') . "\n";
            $msg .= "Interval: {$row['controller_interval']} sec\n";
            $msg .= "Toast: {$row['toast_message']}\n";
            $msg .= "Generated by: {$row['generated_by']}\n";
            $msg .= "Created: {$row['created_at']}";
            sendMessage($chatId, $msg);
        } else {
            sendMessage($chatId, "❌ License not found.");
        }
        $stmt->close();
        break;

    case '/activate':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /activate <license_key>");
            break;
        }
        $key = $arg1;
        $stmt = $conn->prepare("UPDATE licenses SET status=1 WHERE license_key=?");
        $stmt->bind_param("s", $key);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "✅ License `$key` activated.");
        } else {
            sendMessage($chatId, "❌ License not found or already active.");
        }
        $stmt->close();
        break;

    case '/revoke':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /revoke <license_key>");
            break;
        }
        $key = $arg1;
        $stmt = $conn->prepare("UPDATE licenses SET status=0 WHERE license_key=?");
        $stmt->bind_param("s", $key);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "✅ License `$key` revoked (deactivated).");
        } else {
            sendMessage($chatId, "❌ License not found or already inactive.");
        }
        $stmt->close();
        break;

    case '/block':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /block <license_key>");
            break;
        }
        $key = $arg1;
        $stmt = $conn->prepare("UPDATE licenses SET force_logout=1 WHERE license_key=?");
        $stmt->bind_param("s", $key);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "⛔ License `$key` blocked (force logout enabled).");
        } else {
            sendMessage($chatId, "❌ License not found.");
        }
        $stmt->close();
        break;

    case '/unblock':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /unblock <license_key>");
            break;
        }
        $key = $arg1;
        $stmt = $conn->prepare("UPDATE licenses SET force_logout=0 WHERE license_key=?");
        $stmt->bind_param("s", $key);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "✅ License `$key` unblocked.");
        } else {
            sendMessage($chatId, "❌ License not found.");
        }
        $stmt->close();
        break;

    case '/deviceblock':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /deviceblock <device_id>");
            break;
        }
        $deviceId = $arg1;
        $stmt = $conn->prepare("UPDATE devices SET blocked = 1 WHERE device_id = ?");
        $stmt->bind_param("s", $deviceId);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "⛔ Device `$deviceId` blocked.");
        } else {
            sendMessage($chatId, "❌ Device not found or already blocked.");
        }
        $stmt->close();
        break;

    case '/deviceunblock':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /deviceunblock <device_id>");
            break;
        }
        $deviceId = $arg1;
        $stmt = $conn->prepare("UPDATE devices SET blocked = 0 WHERE device_id = ?");
        $stmt->bind_param("s", $deviceId);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "✅ Device `$deviceId` unblocked.");
        } else {
            sendMessage($chatId, "❌ Device not found or not blocked.");
        }
        $stmt->close();
        break;

    case '/blockapp':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /blockapp <package_name>");
            break;
        }
        $package = trim($arg1);
        $stmt = $conn->prepare("INSERT INTO blocked_apps (package_name, blocked_by) VALUES (?, ?) ON DUPLICATE KEY UPDATE blocked_at = NOW(), blocked_by = ?");
        $stmt->bind_param("sss", $package, $chatId, $chatId);
        if ($stmt->execute()) {
            sendMessage($chatId, "⛔ Package `$package` is now blocked globally.");
        } else {
            sendMessage($chatId, "❌ Failed to block package.");
        }
        $stmt->close();
        break;

    case '/unblockapp':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /unblockapp <package_name>");
            break;
        }
        $package = trim($arg1);
        $stmt = $conn->prepare("DELETE FROM blocked_apps WHERE package_name = ?");
        $stmt->bind_param("s", $package);
        if ($stmt->execute() && $stmt->affected_rows > 0) {
            sendMessage($chatId, "✅ Package `$package` is now unblocked.");
        } else {
            sendMessage($chatId, "❌ Package not found or already unblocked.");
        }
        $stmt->close();
        break;

    case '/broadcast':
        if (empty($arg1)) {
            sendMessage($chatId, "Usage: /broadcast <message>");
            break;
        }
        $msg = $arg1 . (isset($parts[2]) ? " " . $parts[2] : "");

        // Get current version
        $verRes = $conn->query("SELECT broadcast_version FROM server_settings WHERE setting_key='broadcast_message'");
        $currentVer = 0;
        if ($verRes && $row = $verRes->fetch_assoc()) {
            $currentVer = (int)$row['broadcast_version'];
        }
        $newVer = $currentVer + 1;

        // Update message and increment version
        $stmt = $conn->prepare("INSERT INTO server_settings (setting_key, setting_value, broadcast_version)
                                VALUES ('broadcast_message', ?, ?)
                                ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), broadcast_version = VALUES(broadcast_version)");
        $stmt->bind_param("si", $msg, $newVer);
        if ($stmt->execute()) {
            sendMessage($chatId, "📢 Broadcast updated to version $newVer:\n$msg");
        } else {
            sendMessage($chatId, "❌ Failed to update broadcast.");
        }
        $stmt->close();
        break;

    // 🆕 Stop broadcast command
    case '/broadcaststop':
        // Set broadcast message to empty and version to 0
        $stmt = $conn->prepare("INSERT INTO server_settings (setting_key, setting_value, broadcast_version)
                                VALUES ('broadcast_message', '', 0)
                                ON DUPLICATE KEY UPDATE setting_value = '', broadcast_version = 0");
        if ($stmt->execute()) {
            sendMessage($chatId, "🛑 Broadcast stopped. No further notifications will be sent.");
        } else {
            sendMessage($chatId, "❌ Failed to stop broadcast.");
        }
        $stmt->close();
        break;

    default:
        sendMessage($chatId, "Unknown command. Send /start for help.");
}

$conn->close();

function sendMessage($chatId, $text) {
    global $apiUrl;
    $data = [
        'chat_id' => $chatId,
        'text' => $text,
        'parse_mode' => 'Markdown'
    ];
    $options = [
        'http' => [
            'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
            'method'  => 'POST',
            'content' => http_build_query($data)
        ]
    ];
    $context = stream_context_create($options);
    file_get_contents($apiUrl . 'sendMessage', false, $context);
}
?>
